// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var Phaser, leftEmitter, rightEmitter;

  Phaser = this.Phaser;

  leftEmitter = void 0;

  rightEmitter = void 0;

  this.GAME = new Phaser.Game({
    scaleMode: Phaser.ScaleManager.SHOW_ALL,
    state: {
      init: function() {
        this.game.plugins.add(Phaser.Plugin.Step);
        this.game.debug.font = '16px monospace';
        this.game.debug.lineHeight = 20;
      },
      preload: function() {
        this.load.baseURL = 'http://examples.phaser.io/assets/';
        this.load.crossOrigin = 'anonymous';
        this.load.image('sky', 'skies/cavern2.png');
        this.load.spritesheet('balls', 'sprites/balls.png', 17, 17);
      },
      create: function() {
        this.add.image(0, 0, 'sky');
        leftEmitter = this.add.emitter(50, this.world.centerY - 200);
        leftEmitter.bounce.setTo(0.5, 0.5);
        leftEmitter.setXSpeed(100, 200);
        leftEmitter.setYSpeed(-50, 50);
        leftEmitter.makeParticles('balls', 0, 250, true, true);
        rightEmitter = this.add.emitter(this.world.width - 50, this.world.centerY - 200);
        rightEmitter.bounce.setTo(0.5, 0.5);
        rightEmitter.setXSpeed(-100, -200);
        rightEmitter.setYSpeed(-50, 50);
        rightEmitter.makeParticles('balls', 1, 250, true, true);
        leftEmitter.start(false, 5000, 20);
        rightEmitter.start(false, 5000, 20);
        this.add.text(20, 560, '[.] Toggle Step', {
          fill: 'white',
          font: this.game.debug.font
        });
      },
      update: function() {
        this.physics.arcade.collide(leftEmitter, rightEmitter, this.change, null, this);
      },
      change: function(a, b) {
        a.frame = 3;
        b.frame = 3;
      }
    }
  });

}).call(this);
