// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var Phaser,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Phaser = this.Phaser;

  Phaser.Plugin.Step = (function(superClass) {
    extend(Step, superClass);

    function Step() {
      return Step.__super__.constructor.apply(this, arguments);
    }

    Step.prototype.keyChar = {
      STEP: "/",
      TOGGLE: "."
    };

    Step.prototype.keyCode = {
      STEP: Phaser.KeyCode.QUESTION_MARK,
      TOGGLE: Phaser.KeyCode.PERIOD
    };

    Step.prototype.init = function() {
      var keyboard;
      keyboard = this.game.input.keyboard;
      this.keyBindings = [];
      this.keyBindings.push(keyboard.addKey(this.keyCode.STEP).onUp.add(this.game.step, this.game));
      this.keyBindings.push(keyboard.addKey(this.keyCode.TOGGLE).onUp.add(this.toggleStep, this));
      this.position = new Phaser.Point(20, 20);
    };

    Step.prototype.render = function() {
      var debug, text;
      debug = this.game.debug;
      if (this.game.stepping) {
        text = "[" + this.keyChar.STEP + "] Step Forward  [" + this.keyChar.TOGGLE + "] Exit Step  Step Count: " + this.game.stepCount;
        debug.text(text, this.position.x, this.position.y, null, debug.font);
      }
    };

    Step.prototype.destroy = function() {
      Step.__super__.destroy.apply(this, arguments);
      this.removeKeyBindings();
    };

    Step.prototype.disableStep = function() {
      this.game.disableStep();
      this.game.debug.reset();
    };

    Step.prototype.enableStep = function() {
      this.game.enableStep();
      this.render();
    };

    Step.prototype.removeKeyBindings = function() {
      var binding, i, len, ref;
      ref = this.keyBindings;
      for (i = 0, len = ref.length; i < len; i++) {
        binding = ref[i];
        binding.detach();
      }
    };

    Step.prototype.toggleStep = function() {
      if (this.game.stepping) {
        this.disableStep();
      } else {
        this.enableStep();
      }
    };

    return Step;

  })(Phaser.Plugin);

}).call(this);
